version: '3.7'
services:
  mysql-db:
    image: mysql
    env_file: ./.env
    environment: 
        - MYSQL_ROOT_PASSWORD=123456
        - MYSQL_DATABASE=guest_book_db
    ports:
      - 3306:3306

  server:
    depends_on: 
        - mysql-db
    build: server
    env_file: ./.env
    ports:
      - '5000:5000'
    # environment:
    #   - DB_HOST=mysql-db
    #   - DB_USER=$MYSQLDB_USER
    #   - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
    #   - DB_NAME=$MYSQLDB_DATABASE
    #   - DB_PORT=3306
    links:
      - mysql-db

  client:
    depends_on: 
        - server
    build: client/guest-book
    ports:
      - '4200:4200'

volumes:
  db: